#include "optical_compensation.hpp"

#include <algorithm>
#include <charconv>
#include <cmath>
#include <fstream>
#include <iterator>
#include <limits>
#include <regex>
#include <stdexcept>
#include <vector>

namespace specs {
namespace {

double numberField(const std::string& json, const std::string& name, bool optional = false) {
    // The interchange file is generated by distortion_model.py, so a focused
    // scalar extractor keeps the native layer dependency-free. This is not a
    // general-purpose JSON parser and intentionally accepts only JSON numbers.
    const std::regex pattern("\\\"" + name + "\\\"\\s*:\\s*"
                             "([-+]?(?:[0-9]+\\.?[0-9]*|\\.[0-9]+)(?:[eE][-+]?[0-9]+)?)");
    std::smatch match;
    if (!std::regex_search(json, match, pattern)) {
        if (optional) return 0.0;
        throw std::runtime_error("missing or invalid JSON field: " + name);
    }
    const double value = std::stod(match[1].str());
    if (!std::isfinite(value)) throw std::runtime_error("non-finite JSON field: " + name);
    return value;
}

float floatField(const std::string& json, const std::string& name) {
    const double value = numberField(json, name);
    if (value < -std::numeric_limits<float>::max() ||
        value > std::numeric_limits<float>::max())
        throw std::runtime_error("JSON field is outside the float range: " + name);
    return static_cast<float>(value);
}

std::uint64_t timestampField(const std::string& json) {
    const std::regex pattern("\\\"timestamp\\\"\\s*:\\s*([^,}\\s]+)");
    std::smatch match;
    if (!std::regex_search(json, match, pattern)) {
        // Distinguish an absent optional timestamp from one with an invalid value.
        if (json.find("\"timestamp\"") == std::string::npos) return 0;
        throw std::runtime_error("invalid JSON field: timestamp");
    }
    const std::string text = match[1].str();
    if (!text.empty() && (text.front() == '-' || text.front() == '+')) {
        if (text.front() == '-') throw std::runtime_error("timestamp is outside the uint64 range");
    }
    std::uint64_t value{};
    const char* begin = text.data() + (!text.empty() && text.front() == '+');
    const char* end = text.data() + text.size();
    const auto parsed = std::from_chars(begin, end, value);
    if (parsed.ec != std::errc{} || parsed.ptr != end)
        throw std::runtime_error("timestamp is outside the uint64 range");
    return value;
}

std::vector<float> matrixField(const std::string& json) {
    const std::regex field("\\\"projection_matrix\\\"\\s*:\\s*\\[([^\\]]*)\\]");
    std::smatch match;
    if (!std::regex_search(json, match, field))
        throw std::runtime_error("missing projection_matrix JSON field");
    const std::regex number("[-+]?(?:[0-9]+\\.?[0-9]*|\\.[0-9]+)(?:[eE][-+]?[0-9]+)?");
    std::vector<float> values;
    for (auto it = std::sregex_iterator(match[1].first, match[1].second, number);
         it != std::sregex_iterator(); ++it) {
        const double value = std::stod(it->str());
        if (!std::isfinite(value) || value < -std::numeric_limits<float>::max() ||
            value > std::numeric_limits<float>::max())
            throw std::runtime_error("projection_matrix value is outside the float range");
        values.push_back(static_cast<float>(value));
    }
    if (values.size() != 16) throw std::runtime_error("projection_matrix must contain 16 numbers");
    return values;
}

}  // namespace

CalibrationParams loadParamsFromJson(const std::string& path) {
    std::ifstream input(path);
    if (!input) throw std::runtime_error("cannot open calibration file: " + path);
    const std::string json((std::istreambuf_iterator<char>(input)), {});
    CalibrationParams params;
    params.k1 = floatField(json, "k1");
    params.k2 = floatField(json, "k2");
    params.k3 = floatField(json, "k3");
    params.p1 = floatField(json, "p1");
    params.p2 = floatField(json, "p2");
    const auto matrix = matrixField(json);
    std::copy(matrix.begin(), matrix.end(), params.projectionMatrix.begin());
    params.timestamp = timestampField(json);
    return params;
}

GlId createCorrectiveShaderProgram(GraphicsApi& graphics, const std::string& vertexSource,
                                   const std::string& fragmentSource) {
    const GlId vertex = graphics.compileShader(0x8B31, vertexSource);  // GL_VERTEX_SHADER
    GlId fragment{};
    try {
        fragment = graphics.compileShader(0x8B30, fragmentSource);  // GL_FRAGMENT_SHADER
        const GlId program = graphics.linkProgram(vertex, fragment);
        graphics.deleteShader(vertex);
        graphics.deleteShader(fragment);
        return program;
    } catch (...) {
        graphics.deleteShader(vertex);
        if (fragment) graphics.deleteShader(fragment);
        throw;
    }
}

void bindUniforms(GraphicsApi& graphics, GlId program, const CalibrationParams& params) {
    graphics.useProgram(program);
    graphics.uniform1f(program, "k1", params.k1);
    graphics.uniform1f(program, "k2", params.k2);
    graphics.uniform1f(program, "k3", params.k3);
    graphics.uniform1f(program, "p1", params.p1);
    graphics.uniform1f(program, "p2", params.p2);
    // Python serializes rows; OpenGL expects columns, hence transpose=true.
    graphics.uniformMatrix4(program, "uProjectionMatrix", params.projectionMatrix.data(), true);
}

void updateDynamicUniforms(GraphicsApi& graphics, GlId program, const SensorData& sensor) {
    graphics.useProgram(program);
    graphics.uniform2f(program, "uEyeOffset", sensor.eyeOffsetX, sensor.eyeOffsetY);
}

void runCorrectivePipeline(GraphicsApi& graphics, GlId program, CalibrationParams params,
                           const PipelineCallbacks& callbacks, int vertexCount) {
    if (!callbacks.deviceIsRunning || !callbacks.pollDeviceSensors || !callbacks.captureFrame ||
        !callbacks.presentFrame || !callbacks.synchronizeFrameTiming)
        throw std::invalid_argument("pipeline callbacks must be configured");
    if (vertexCount <= 0) throw std::invalid_argument("vertexCount must be positive");

    bindUniforms(graphics, program, params);
    while (callbacks.deviceIsRunning()) {
        // Sample sensors before capture so the correction applied to this frame
        // reflects the freshest available eye pose and calibration state.
        const SensorData sensor = callbacks.pollDeviceSensors();
        const FrameData frame = callbacks.captureFrame();
        if (sensor.calibrationChanged) {
            if (!callbacks.updateCalibration)
                throw std::invalid_argument("calibration update callback is not configured");
            params = callbacks.updateCalibration(sensor);
            bindUniforms(graphics, program, params);
        }
        params.eyeOffsetX = sensor.eyeOffsetX;
        params.eyeOffsetY = sensor.eyeOffsetY;
        updateDynamicUniforms(graphics, program, sensor);
        graphics.bindTexture(frame.texture);
        graphics.useProgram(program);
        graphics.drawTriangles(vertexCount);
        callbacks.presentFrame();
        callbacks.synchronizeFrameTiming();
    }
}

}  // namespace specs
